increase code coverage, update pr workflows

diff --git a/.github/workflows/pr-build-modules.yml b/.github/workflows/pr-build-modules.yml
--- a/.github/workflows/pr-build-modules.yml
+++ b/.github/workflows/pr-build-modules.yml
@@ -19,9 +19,6 @@ jobs:
       modules: ${{ steps.set-modules.outputs.modules }}
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-go@v5
-        with:
-          go-version: ${{ env.GO_VERSION }}
       - id: set-modules
         run: |
           echo "modules=$(find . -name go.mod -d -not -path "./sample-apps/*" -not -path "./sampleapp/*" | sed -r 's|/[^/]+$||' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
@@ -47,7 +44,6 @@ jobs:
     needs: detect-modules-to-lint-and-test
     strategy:
       matrix:
-        module: ${{ fromJSON(needs.detect-modules-to-lint-and-test.outputs.modules) }}
         go-version: ["1.24.0", "1.23.0", "~1.22.4"]
         platform:
           - os: ubuntu-latest
@@ -70,18 +66,38 @@ jobs:
 
     - name: Run tests for Module with Coverage
       if: matrix.platform.os == 'windows-latest'
-      working-directory: ${{ matrix.module }}
+      shell: bash
       env:
         GOARCH: ${{ matrix.platform.arch }}
       run: |
-        go test -cover -race ./...
+        rootDir=$(pwd)
+        for module in ${{ join(fromJSON(needs.detect-modules-to-lint-and-test.outputs.modules), ' ') }}
+        do
+          cd $module
+          go test -cover -race ./...
+          cd $rootDir
+        done
 
     - name: Run tests for Module and Generate Detailed Coverage Report
       if: matrix.platform.os != 'windows-latest'
-      working-directory: ${{ matrix.module }}
+      shell: bash
       env:
         GOARCH: ${{ matrix.platform.arch }}
       run: |
-        go test -coverprofile=coverage.out -race ./...
-        go tool cover -func=coverage.out
-        go tool cover -html=coverage.out -o coverage.html
+        rootDir=$(pwd)
+        for module in ${{ join(fromJSON(needs.detect-modules-to-lint-and-test.outputs.modules), ' ') }}
+        do
+          cd $module
+          go test -coverprofile=coverage.out -race ./...
+          go tool cover -func=coverage.out > go_tool_coverage_output.txt
+          cat go_tool_coverage_output.txt
+          coverage=$(cat go_tool_coverage_output.txt | fgrep total | awk '{print substr($3, 1, length($3)-1)}')
+          coverage_rounded=$(printf '%.0f' $coverage)
+          echo "The Module Coverage is $coverage_rounded%"
+          min_coverage=80 # this is 80.00%
+          if [[ coverage_rounded -lt min_coverage ]]; then
+            echo "Module Coverage ($coverage_rounded%) is less than the required minimum coverage ($min_coverage%)"
+            exit 1
+          fi
+          cd $rootDir
+        done
